# Generated by Django 3.2.8 on 2021-12-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_email_verify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default=True, max_length=150, null=True),
        ),
    ]
