# Generated by Django 3.2.8 on 2021-12-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_email_verify', '0002_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
