# Generated by Django 4.0 on 2021-12-17 07:29

from django.db import migrations, models
import typing


class Migration(migrations.Migration):

    dependencies = [
        ('auth_email_verify', '0003_remove_profile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name='AuthRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('permission_list', models.ManyToManyField(to='auth_email_verify.AuthPermission')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
