# Generated by Django 4.0 on 2021-12-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_email_verify', '0004_authpermission_authrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpermission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authrole',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
