# Generated by Django 4.0 on 2021-12-18 10:37

from django.db import migrations, models
import django.db.models.deletion
import typing


class Migration(migrations.Migration):

    dependencies = [
        ('auth_email_verify', '0005_alter_authpermission_id_alter_authrole_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perm_slug', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.RemoveField(
            model_name='authrole',
            name='permission_list',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='permission_objs', to='auth_email_verify.authrole'),
        ),
    ]
