# Generated by Django 3.2.8 on 2021-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], max_length=300, null=True),
        ),
    ]
