# Generated by Django 4.0 on 2021-12-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_date',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_birth',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='id_number',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
